name: Update README

on:
	schedule:
		- cron:  '30  6 * * *'

jobs:
	commit:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout repository
				uses: actions/checkout@v5


			- name: Update file and commit
				run: |